version: "3"

#networks:
#  dnmp-network

services:
  nginx:
    build: ./nginx
    container_name: dnmp-nginx
    restart: always
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
      - "8889:8889"
#    networks:
#      - dnmp-network
    depends_on:
      - "php"
    volumes:
      #      - ../www:/var/www/html
      - /d/laragon/www:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../logs/nginx:/var/log/nginx
  php:
    build: ./php
    container_name: dnmp-php
    restart: always
    command: php-fpm
    ports:
      - "9000:9000"
#    networks:
#      - dnmp-network
    #    depends_on:
    #      - "mysql"
    #      - "redis"
    volumes:
      #      - ../www:/var/www/html
      - /d/laragon/www:/var/www/html
#      - ./php/conf/php.ini:/usr/local/etc/php/php.ini
#      - ./php/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
#      - ./php/conf.d/:/usr/local/etc/php/conf.d/
      - ../logs/php-fpm:/var/log/php-fpm
#  mysql:
#    image: mysql:5.7
#    container_name: dnmp-mysql
#    ports:
#      - "3306:3306"
#    networks:
#      - dnmp-network
#    volumes:
#      - ~/mysql/mydata:/var/lib/mysql
#      - ~/mysql/dbdump:/root
#    environment:
#      MYSQL_ROOT_PASSWORD: "123456"
#  redis:
#    image: redis:3.0-alpine
#    container_name: dnmp-redis
#    ports:
#      - "6379:6379"
#    networks:
#      - dnmp-network
#    volumes:
#      - ~/docker_data/redis:/data